### ISSUE TITLE
Cannot find module 'typescript'

### ISSUE THREAD

**Issue by dfa1234** [ionic-team/v4-migration-tslint#43]
Running
`npx tslint -c ionic-migration.json -p tsconfig.json`
Return 
`npx: installed 40 in 0.853s
Cannot find module 'typescript'
`
My ionic info:
```
✗ 
[ERROR] Error loading @ionic/app-scripts package.json: Error: Cannot find module '@ionic/app-scripts/package'

Ionic:

   ionic (Ionic CLI)  : 4.0.1 (/usr/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0, browser 5.0.3

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v10.6.0 (/usr/bin/node)
   npm               : 6.2.0
   OS                : Linux 4.15

Environment:

   ANDROID_HOME : /home/dfa/Android/Sdk
`
```

**Comment by dfa1234** [comment]
For the record,
I had a new problem running `npx tslint -c ionic-migration.json -p tsconfig.json`
Saying 
```
{ Error: Cannot find module 'codelyzer/angular/ngWalker'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/dfa/repositories/galien-mobile-migration/node_modules/@ionic/v4-migration-tslint/rules/ionBackButtonNotAddedByDefaultRule.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }
```

I resolved it running 
```
npm i codelyzer tslint @angular/compiler @angular/core
```
